---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: simulate-ss
  labels:
    app.kubernetes.io/name: simulate-ss
    app.kubernetes.io/instance: process-control
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/component: simulate
    app.kubernetes.io/part-of: process-control
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: simulate
      app.kubernetes.io/instance: process-control
      app.kubernetes.io/part-of: process-control
  serviceName: "simulate-service"
  replicas: 1
  minReadySeconds: 10
  template:
    metadata:
      labels:
        app.kubernetes.io/name: simulate
        app.kubernetes.io/instance: process-control
        app.kubernetes.io/part-of: process-control
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: simulate
          image: quay.io/device-edge-workshops/process-control-simulate-k8s:1.1.0
          env:
            - name: MQTT_URI
              value: mqtt://mqtt
          ports:
            - containerPort: 1880
              name: simulate-port
          resources:
            limits:
              memory: "100Mi"
              cpu: "100m"
