---
- name: Install cluster via mounting media
  hosts:
    - servers
  gather_facts: false
  connection: local
  tasks:
    - name: Run OS install
      dellemc.openmanage.idrac_os_deployment:
        idrac_ip: "{{ idrac_address }}"
        idrac_user: "{{ idrac_auth.username }}"
        idrac_password: "{{ idrac_auth.password }}"
        validate_certs: false
        share_name: "10.1.3.106:/mnt/storage/nfs"
        iso_image: agent.x86_64.iso
        expose_duration: 240