{{ if .Values.certManager }}
{{ if .Values.issueAPICert }}
---
apiVersion: config.openshift.io/v1
kind: APIServer
metadata:
  name: cluster
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  servingCerts:
    namedCertificates:
      - names:
          - api.{{ .Values.clusterSettings.baseURL }}
        servingCertificate:
          name: openshift-api-cert
{{ end }}
{{ end }}