{{ if .Values.certManager }}
{{ if .Values.certManager.issueAPICert }}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: openshift-api
  namespace: openshift-config
  annotations:
    argocd.argoproj.io/sync-wave: "3"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  dnsNames:
    - api.{{ .Values.clusterSettings.baseURL }}
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: {{ .Values.certManager.issuer.name }}
  secretName: openshift-api-cert
{{ end }}
{{ if .Values.certManager.issueIngressCert }}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: router-default
  namespace: openshift-ingress
  annotations:
    argocd.argoproj.io/sync-wave: "3"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  dnsNames:
      - apps.{{ .Values.clusterSettings.baseURL }}
      - "*.apps.{{ .Values.clusterSettings.baseURL }}"
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: {{ .Values.certManager.issuer.name }}
  secretName: router-cert
{{ end }}
{{ end }}