---
deploymentNumber: '1'
displayName: "Customer_Three"
companyName: "Customer_Three"
billingAddress: "One Microsoft Way"
billingCity: "Redmond"
billingState: "Washington"
billingZipCode: "98052"
deploymentAddress: "One Microsoft Way"
deploymentCity: "Redmond"
deploymentState: "Washington"
deploymentZipCode: "98052"
serviceProvider: "Managed_Services_Inc"
namespace: "customer-3"