---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: acp-standard-services
  namespace: openshift-gitops
  labels:
    application: acp-standard-services
spec:
  destination:
    name: ""
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://github.com/RedHatEdge/patterns.git
    targetRevision: HEAD
    path: blocks/acp-rh-core-services-install/code/acp-standard-services
    helm:
      values: |
{{- toYaml .Values | nindent 8 }}