---
apiVersion: v1
kind: Secret
metadata:
  name: acp-standard-services-code
  namespace: openshift-gitops
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: git
  url: https://github.com/RedHatEdge/patterns.git