---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: process-control
  namespace: openshift-gitops
  labels:
    application: process-control
spec:
  destination:
    name: ""
    namespace: process-control
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://github.com/RedHatEdge/patterns.git
    targetRevision: HEAD
    path: blocks/k8s-core-concepts/code/k8s
    destination:
      server: https://kubernetes.default.svc
      namespace: process-control
