---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: process-control
  namespace: openshift-gitops
  labels:
    application: process-control
spec:
  destination:
    name: ""
    namespace: process-control
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://github.com/RedHatEdge/patterns.git
    targetRevision: HEAD
    path: blocks/helm-getting-started/code/chart
    helm:
      parameters:
        instanceAnnotations:
          companyName: "Example_Gitops_Company_Deployment"
          billingAddress: "100_East_Davie_Street"
          billingCity: "Raleigh"
          billingState: "North Carolina"
          billingZipCode: "27601"
          billingCountry: "US"
          deploymentAddress: "30_36_Monument_Street"
          deploymentCity: "London"
          deploymentState: "NA"
          deploymentZipCode: " EC3R_8NB"
          deploymentCountry: "UK"
          serviceProvider: "Managed_GitOps_Services_Inc"