{{ if .Values.certManager.secrets }}
{{- range .Values.certManager.secrets }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .name }}
  namespace: cert-manager
  annotations:
    argocd.argoproj.io/sync-wave: "1"
stringData:
{{- toYaml .stringData | nindent 2 }}
{{- end }}
{{ end }}
