{{ if .Values.convergedStorage }}
---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: ocs-public-cluster
  namespace: openshift-storage
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  config: '{
  	"cniVersion": "0.3.1",
  	"type": "macvlan",
  	"master": "{{ .Values.convergedStorage.interface }}",
  	"mode": "bridge",
  	"ipam": {
    	    "type": "whereabouts",
    	    "range": "{{ .Values.convergedStorage.network }}"
  	}
  }'
{{ end }}