---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: control-ss
  labels:
    app.kubernetes.io/name: control-ss
    app.kubernetes.io/instance:
    app.kubernetes.io/version: "4.0.0"
    app.kubernetes.io/component: control
    app.kubernetes.io/part-of: process-control
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: control
      app.kubernetes.io/instance:
      app.kubernetes.io/part-of: process-control
  serviceName: "control-service"
  replicas: 1
  minReadySeconds: 10
  template:
    metadata:
      labels:
        app.kubernetes.io/name: control
        app.kubernetes.io/instance: process-control
        app.kubernetes.io/part-of: process-control
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: control
          image: quay.io/device-edge-workshops/process-control-control-k8s:4.1.0
          env:
            - name: MQTT_URI
              value: mqtt://mqtt
          ports:
            - containerPort: 1880
              name: control-port
          resources:
            limits:
              memory: "250Mi"
              cpu: "100m"
