---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: control-ss-{{ .Release.Name }}
  labels:
    app.kubernetes.io/name: control-ss-{{ .Release.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: "4.0.0"
    app.kubernetes.io/component: control
    app.kubernetes.io/part-of: process-control
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: control-{{ .Release.Name }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/part-of: process-control
  serviceName: "control-service"
  replicas: 1
  minReadySeconds: 10
  template:
    metadata:
      labels:
        app.kubernetes.io/name: control-{{ .Release.Name }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/part-of: process-control
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: control
          image: quay.io/device-edge-workshops/process-control-control-k8s:4.1.0
          env:
            - name: MQTT_URI
              value: mqtt://mqtt-{{ .Release.Name }}
          ports:
            - containerPort: 1880
              name: control-port
          resources:
            limits:
              memory: {{ .Values.resourceLimitOverrides.control.memory | default "250Mi" }}
              cpu: {{ .Values.resourceLimitOverrides.control.cpu | default "100m" }}
