---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: simulate-ss
  labels:
    app.kubernetes.io/name: simulate-ss
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/component: simulate
    app.kubernetes.io/part-of: process-control
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: simulate
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/part-of: process-control
  serviceName: "simulate-service"
  replicas: 1
  minReadySeconds: 10
  template:
    metadata:
      labels:
        app.kubernetes.io/name: simulate
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/part-of: process-control
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: simulate
          image: quay.io/device-edge-workshops/process-control-simulate-k8s:1.0.0
          resources:
            limits:
              memory: {{ .Values.resourceLimitOverrides.control.memory | default "100Mi" }}
              cpu: {{ .Values.resourceLimitOverrides.control.cpu | default "100m" }}
