---

rendezvous_ip: 172.16.2.2
pull_secret: 'your-pull-secret'
ssh_key: 'your-ssh-key'

cluster_info:
  name: example-cluster
  version: stable
  base_domain: your-domain.com
  masters: 3
  workers: 0
  api_ip: 172.16.2.10
  ingress_ip: 172.16.2.11
  host_network_cidr: 172.16.2.0/23

nodes:
  - name: node0
    cluster_link:
      mac_address: b8:ca:3a:6e:69:40
      ip_address: 172.16.2.2
  - name: node1
    cluster_link:
      mac_address: 24:6e:96:69:56:90
      ip_address: 172.16.2.3
  - name: node2
    cluster_link:
      mac_address: b8:ca:3a:6e:17:d8
      ip_address: 172.16.2.4

all_nodes_settings:
  installation_device: /dev/disk/by-path/pci-0000:02:00.0-scsi-0:2:0:0
  cluster_link:
    interface: eno1
    subnet_length: 23
  dns_servers:
    - 8.8.8.8
    - 8.8.4.4
  routes:
    - destination: 0.0.0.0/0
      router_address: 172.16.2.1
      interface: eno1
      table_id: 254
  architecture: amd64
  hyperthreading: 'Enabled'
