---
deploymentNumber: '1'
displayName: "customer_one"
companyName: "Customer One"
billingAddress: "100_East_Davie_Street"
billingCity: "Raleigh"
billingState: "North Carolina"
billingZipCode: "27601"
deploymentAddress: "Werner-von-Siemens-Ring_12"
deploymentCity: "Munich"
deploymentState: "Grasbrunn"
deploymentZipCode: "85630"
serviceProvider: "Managed_Services_Inc"
namespace: "customer-1"